image: 'rust:latest'

stages:
  - build
  - test
  - wasm

build:
  stage: build
  script:
    - rustc --version
    - cargo --version
    - rustup --version
    - cargo build --all --verbose

test:
  stage: test
  script:
    - cargo test --all --verbose

wasm:
  stage: wasm
  script:
    - cargo check
    - cargo check --target wasm32-unknown-unknown
    - cargo check --target wasm32-unknown-unknown --no-default-features --features "console_error_panic_hook wee_alloc"

