image: 'rust:latest'

stages:
  - build
  - test
  - wasm-check

build:
  stage: build
  cache:
    paths:
      - cargo/
      - target/
  script:
    - rustc --version
    - cargo --version
    - rustup --version
    - cargo build --all --verbose

test:
  stage: test
  script:
    - cargo test --all --verbose

wasm-check:
  stage: wasm-check
  before_script:
    - wasm-pack build
  script:
    - cargo check
    - cargo check --target wasm32-unknown-unknown
    - cargo check --target wasm32-unknown-unknown --no-default-features --features "console_error_panic_hook wee_alloc"
    - wasm-pack test --headless --firefox
