image: 'rust:latest'

stages:
  - build
  - test
#  - wasm-check

build:
  stage: build
  cache:
    paths:
      - cargo/
      - target/
  script:
    - rustc --version
    - cargo --version
    - rustup --version
    - rustup default
    - cargo build --all --verbose

test:
  stage: test
  script:
    - cargo test --all --verbose

#wasm-check:
#  stage: wasm-check
#
#  variables:
#    APT_CACHE_DIR: apt-cache
#
#  before_script:
#    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
#    - rustup update
#    - rustup toolchain install nightly
#    - rustup target add wasm32-unknown-unknown --toolchain nightly
#    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
#    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y firefox-esr
#    - firefox --version
#  script:
#    - cargo check
#    - wasm-pack build
#    - wasm-pack test --firefox --headless --verbose
#    - cargo check --target wasm32-unknown-unknown
#    - cargo check --target wasm32-unknown-unknown --no-default-features --features "console_error_panic_hook wee_alloc"
#  cache:
#    paths:
#      - apt-cache