use super::{cpu::ThumbInstructionFormat};

pub const THUMB_INSTRUCTIONS: [ThumbInstructionFormat; 256] = [
//0000 0000
ThumbInstructionFormat::MoveShiftedRegister, ThumbInstructionFormat::MoveShiftedRegister, ThumbInstructionFormat::MoveShiftedRegister, ThumbInstructionFormat::MoveShiftedRegister,
ThumbInstructionFormat::MoveShiftedRegister, ThumbInstructionFormat::MoveShiftedRegister,ThumbInstructionFormat::MoveShiftedRegister,ThumbInstructionFormat::MoveShiftedRegister,
ThumbInstructionFormat::MoveShiftedRegister,ThumbInstructionFormat::MoveShiftedRegister,ThumbInstructionFormat::MoveShiftedRegister,ThumbInstructionFormat::MoveShiftedRegister,
ThumbInstructionFormat::MoveShiftedRegister,ThumbInstructionFormat::MoveShiftedRegister,ThumbInstructionFormat::MoveShiftedRegister,ThumbInstructionFormat::MoveShiftedRegister,
//0001 0000
ThumbInstructionFormat::MoveShiftedRegister, ThumbInstructionFormat::MoveShiftedRegister,ThumbInstructionFormat::MoveShiftedRegister,ThumbInstructionFormat::MoveShiftedRegister,
ThumbInstructionFormat::MoveShiftedRegister,ThumbInstructionFormat::MoveShiftedRegister,ThumbInstructionFormat::MoveShiftedRegister,ThumbInstructionFormat::MoveShiftedRegister,
ThumbInstructionFormat::AddSubtract, ThumbInstructionFormat::AddSubtract,ThumbInstructionFormat::AddSubtract,ThumbInstructionFormat::AddSubtract,
ThumbInstructionFormat::AddSubtract,ThumbInstructionFormat::AddSubtract,ThumbInstructionFormat::AddSubtract,ThumbInstructionFormat::AddSubtract,
//0010 0000
ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,
ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,
ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,
ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,
//0011 0000
ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,
ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,
ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,
ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,ThumbInstructionFormat::ImmediateOp,
//0100 0000
ThumbInstructionFormat::ALU,ThumbInstructionFormat::ALU,ThumbInstructionFormat::ALU,ThumbInstructionFormat::ALU,
ThumbInstructionFormat::HiRegister,ThumbInstructionFormat::HiRegister,ThumbInstructionFormat::HiRegister,ThumbInstructionFormat::HiRegister,
ThumbInstructionFormat::LoadPC,ThumbInstructionFormat::LoadPC,ThumbInstructionFormat::LoadPC,ThumbInstructionFormat::LoadPC,
ThumbInstructionFormat::LoadPC,ThumbInstructionFormat::LoadPC,ThumbInstructionFormat::LoadPC,ThumbInstructionFormat::LoadPC,
//0101 0000
ThumbInstructionFormat::LoadStoreOffset, ThumbInstructionFormat::LoadStoreOffset,  ThumbInstructionFormat::LoadStoreHalfWord,ThumbInstructionFormat::LoadStoreHalfWord,
ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreExtended,ThumbInstructionFormat::LoadStoreExtended,
ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreImmediateOffset, ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreOffset,
ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreHalfWord,ThumbInstructionFormat::LoadStoreHalfWord,
//0110 0000
ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreImmediateOffset,
ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreImmediateOffset,
ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreImmediateOffset,
ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreImmediateOffset,ThumbInstructionFormat::LoadStoreImmediateOffset,
//0111 0000
ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreOffset,
ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreOffset,
ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreOffset,
ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreOffset,ThumbInstructionFormat::LoadStoreOffset,
//1000 0000
ThumbInstructionFormat::LoadStoreHalfWord,ThumbInstructionFormat::LoadStoreHalfWord,ThumbInstructionFormat::LoadStoreHalfWord,ThumbInstructionFormat::LoadStoreHalfWord,
ThumbInstructionFormat::LoadStoreHalfWord,ThumbInstructionFormat::LoadStoreHalfWord,ThumbInstructionFormat::LoadStoreHalfWord,ThumbInstructionFormat::LoadStoreHalfWord,
ThumbInstructionFormat::LoadStoreHalfWord,ThumbInstructionFormat::LoadStoreHalfWord,ThumbInstructionFormat::LoadStoreHalfWord,ThumbInstructionFormat::LoadStoreHalfWord,
ThumbInstructionFormat::LoadStoreHalfWord,ThumbInstructionFormat::LoadStoreHalfWord,ThumbInstructionFormat::LoadStoreHalfWord,ThumbInstructionFormat::LoadStoreHalfWord,
//1001 0000
ThumbInstructionFormat::LoadStoreSP,ThumbInstructionFormat::LoadStoreSP,ThumbInstructionFormat::LoadStoreSP,ThumbInstructionFormat::LoadStoreSP,
ThumbInstructionFormat::LoadStoreSP,ThumbInstructionFormat::LoadStoreSP,ThumbInstructionFormat::LoadStoreSP,ThumbInstructionFormat::LoadStoreSP,
ThumbInstructionFormat::LoadStoreSP,ThumbInstructionFormat::LoadStoreSP,ThumbInstructionFormat::LoadStoreSP,ThumbInstructionFormat::LoadStoreSP,
ThumbInstructionFormat::LoadStoreSP,ThumbInstructionFormat::LoadStoreSP,ThumbInstructionFormat::LoadStoreSP,ThumbInstructionFormat::LoadStoreSP,
//1010 0000
ThumbInstructionFormat::LoadAddress,ThumbInstructionFormat::LoadAddress,ThumbInstructionFormat::LoadAddress,ThumbInstructionFormat::LoadAddress,
ThumbInstructionFormat::LoadAddress,ThumbInstructionFormat::LoadAddress,ThumbInstructionFormat::LoadAddress,ThumbInstructionFormat::LoadAddress,
ThumbInstructionFormat::LoadAddress,ThumbInstructionFormat::LoadAddress,ThumbInstructionFormat::LoadAddress,ThumbInstructionFormat::LoadAddress,
ThumbInstructionFormat::LoadAddress,ThumbInstructionFormat::LoadAddress,ThumbInstructionFormat::LoadAddress,ThumbInstructionFormat::LoadAddress,
//1011 0000
ThumbInstructionFormat::LoadAddress,ThumbInstructionFormat::Undefined,ThumbInstructionFormat::Undefined,ThumbInstructionFormat::Undefined, 
ThumbInstructionFormat::PushPopRegister, ThumbInstructionFormat::PushPopRegister,ThumbInstructionFormat::Undefined,ThumbInstructionFormat::Undefined,
ThumbInstructionFormat::Undefined,ThumbInstructionFormat::Undefined,ThumbInstructionFormat::Undefined,ThumbInstructionFormat::Undefined,
ThumbInstructionFormat::PushPopRegister, ThumbInstructionFormat::PushPopRegister, ThumbInstructionFormat::BreakpointInterrupt,ThumbInstructionFormat::Undefined,
//1100 0000
ThumbInstructionFormat::MultipleLoadStore,ThumbInstructionFormat::MultipleLoadStore,ThumbInstructionFormat::MultipleLoadStore,ThumbInstructionFormat::MultipleLoadStore,
ThumbInstructionFormat::MultipleLoadStore,ThumbInstructionFormat::MultipleLoadStore,ThumbInstructionFormat::MultipleLoadStore,ThumbInstructionFormat::MultipleLoadStore,
ThumbInstructionFormat::MultipleLoadStore,ThumbInstructionFormat::MultipleLoadStore,ThumbInstructionFormat::MultipleLoadStore,ThumbInstructionFormat::MultipleLoadStore,
ThumbInstructionFormat::MultipleLoadStore,ThumbInstructionFormat::MultipleLoadStore,ThumbInstructionFormat::MultipleLoadStore,ThumbInstructionFormat::MultipleLoadStore,
//1101 0000
ThumbInstructionFormat::ConditionalBranch,ThumbInstructionFormat::ConditionalBranch,ThumbInstructionFormat::ConditionalBranch,ThumbInstructionFormat::ConditionalBranch,
ThumbInstructionFormat::ConditionalBranch,ThumbInstructionFormat::ConditionalBranch,ThumbInstructionFormat::ConditionalBranch,ThumbInstructionFormat::ConditionalBranch,
ThumbInstructionFormat::ConditionalBranch,ThumbInstructionFormat::ConditionalBranch,ThumbInstructionFormat::ConditionalBranch,ThumbInstructionFormat::ConditionalBranch,
ThumbInstructionFormat::ConditionalBranch,ThumbInstructionFormat::ConditionalBranch,ThumbInstructionFormat::Undefined,ThumbInstructionFormat::BreakpointInterrupt,
//1110 0000
ThumbInstructionFormat::UnConditonalBranch,ThumbInstructionFormat::UnConditonalBranch,ThumbInstructionFormat::UnConditonalBranch,ThumbInstructionFormat::UnConditonalBranch,
ThumbInstructionFormat::UnConditonalBranch,ThumbInstructionFormat::UnConditonalBranch,ThumbInstructionFormat::UnConditonalBranch,ThumbInstructionFormat::UnConditonalBranch,
ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,
ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,
//1111 0000
ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,
ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,
ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,
ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink,ThumbInstructionFormat::LongBranchLink
];