[package]
name = "desktop-frontend"
version = "0.1.0"
authors = ["Eric Nowac <enowac@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gba-emulator = {path = "../"}